"use client";

import { useEffect, useRef } from "react";

/**
 * Mounts the Pagefind UI into the DOM via a dynamic script load.
 * Pagefind's JS and CSS are served from /pagefind/ (generated by postbuild).
 * We load both assets dynamically so the static export doesn't need them at
 * build time (they only exist after `pagefind --site out` runs).
 */
export default function SearchInput() {
  const containerRef = useRef<HTMLDivElement>(null);
  const initialised = useRef(false);

  useEffect(() => {
    if (initialised.current) return;
    initialised.current = true;

    // Load Pagefind CSS
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "/pagefind/pagefind-ui.css";
    document.head.appendChild(link);

    // Load Pagefind UI JS then initialise
    const script = document.createElement("script");
    script.src = "/pagefind/pagefind-ui.js";
    script.onload = () => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Pagefind UI is loaded dynamically, no types available
      if (containerRef.current && (window as any).PagefindUI) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        new (window as any).PagefindUI({
          element: containerRef.current,
          showImages: false,
          excerptLength: 20,
          resetStyles: false,
        });
      }
    };
    document.head.appendChild(script);
  }, []);

  return <div ref={containerRef} />;
}
